#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["ElectricManagement.Api/ElectricManagement.Api.csproj", "ElectricManagement.Api/"]
COPY ["ElectricManagement.Domain/ElectricManagement.Domain.csproj", "ElectricManagement.Domain/"]
COPY ["ElectricManagement.Infrastructure/ElectricManagement.Infrastructure.csproj", "ElectricManagement.Infrastructure/"]
RUN dotnet restore "ElectricManagement.Api/ElectricManagement.Api.csproj"
COPY . .
WORKDIR "/src/ElectricManagement.Api"
RUN dotnet build "ElectricManagement.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ElectricManagement.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ElectricManagement.Api.dll"]